-- Dimensional model for music_dw (PostgreSQL). Executable and idempotent (IF NOT EXISTS / ON CONFLICT).
-- Design record: docs/dimensional_model.md   |   Requirements: R1-R3 (docs/requirements.md)
-- Two fact tables share the conformed dimension dim_artist (fact constellation, drill-across by artist).

CREATE SCHEMA IF NOT EXISTS dw;

-- ---------------------------------------------------------------- DIMENSIONS
-- Conformed dimension: the integration point between Spotify and Grammy (business key = normalized name).
CREATE TABLE IF NOT EXISTS dw.dim_artist (
    artist_key         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,   -- surrogate
    artist_match_key   TEXT    NOT NULL UNIQUE,                                -- business key (normalized name)
    artist_name        TEXT    NOT NULL,                                       -- representative display name
    artist_type        TEXT    NOT NULL DEFAULT 'REAL'
                       CHECK (artist_type IN ('REAL', 'PLACEHOLDER', 'UNKNOWN')),
    has_spotify_tracks BOOLEAN NOT NULL DEFAULT FALSE,                         -- integration indicators
    has_grammy_awards  BOOLEAN NOT NULL DEFAULT FALSE
);
-- Unknown member: Grammy rows without artist keep their award instead of being dropped.
INSERT INTO dw.dim_artist (artist_key, artist_match_key, artist_name, artist_type)
VALUES (-1, '__unknown__', 'Unknown (no artist in source)', 'UNKNOWN')
ON CONFLICT (artist_key) DO NOTHING;
-- Placeholder member: generic credits that do not identify an act (e.g. "(Various Artists)", "Original Cast").
INSERT INTO dw.dim_artist (artist_key, artist_match_key, artist_name, artist_type)
VALUES (-2, '__placeholder__', 'Generic credit (Various Artists, Original Cast)', 'PLACEHOLDER')
ON CONFLICT (artist_key) DO NOTHING;

CREATE TABLE IF NOT EXISTS dw.dim_genre (
    genre_key  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS dw.dim_track (
    track_key   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    track_id    TEXT    NOT NULL UNIQUE,            -- Spotify business key
    track_name  TEXT,
    album_name  TEXT,
    explicit    BOOLEAN,
    duration_ms INTEGER CHECK (duration_ms IS NULL OR duration_ms >= 0)
);

CREATE TABLE IF NOT EXISTS dw.dim_category (
    category_key  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name TEXT NOT NULL UNIQUE
);

-- Ceremony year: natural key (a year is stable and meaningful by itself).
CREATE TABLE IF NOT EXISTS dw.dim_year (
    year_key       SMALLINT PRIMARY KEY CHECK (year_key BETWEEN 1950 AND 2100),
    decade         SMALLINT NOT NULL,
    ceremony_title TEXT
);

-- --------------------------------------------------------------------- FACTS
-- Grain: one row per Spotify credit = distinct (track, artist, genre).
CREATE TABLE IF NOT EXISTS dw.fact_track_credit (
    track_credit_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    track_key        INTEGER  NOT NULL REFERENCES dw.dim_track(track_key),
    artist_key       INTEGER  NOT NULL REFERENCES dw.dim_artist(artist_key),
    genre_key        INTEGER  NOT NULL REFERENCES dw.dim_genre(genre_key),
    popularity       SMALLINT NOT NULL CHECK (popularity BETWEEN 0 AND 100),
    danceability     NUMERIC(5,4) NOT NULL CHECK (danceability BETWEEN 0 AND 1),
    energy           NUMERIC(5,4) NOT NULL CHECK (energy       BETWEEN 0 AND 1),
    valence          NUMERIC(5,4) NOT NULL CHECK (valence      BETWEEN 0 AND 1),
    acousticness     NUMERIC(5,4) NOT NULL CHECK (acousticness BETWEEN 0 AND 1),
    CONSTRAINT uq_fact_track_credit_grain UNIQUE (track_key, artist_key, genre_key)
);
CREATE INDEX IF NOT EXISTS ix_ftc_artist ON dw.fact_track_credit (artist_key);
CREATE INDEX IF NOT EXISTS ix_ftc_genre  ON dw.fact_track_credit (genre_key);

-- Grain: one row per Grammy award credit = (award entry, credited artist).
CREATE TABLE IF NOT EXISTS dw.fact_grammy_award (
    award_credit_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    award_id         INTEGER  NOT NULL,                       -- degenerate: source_row_id of grammy_awards
    artist_key       INTEGER  NOT NULL REFERENCES dw.dim_artist(artist_key),   -- -1 = unknown
    category_key     INTEGER  NOT NULL REFERENCES dw.dim_category(category_key),
    year_key         SMALLINT NOT NULL REFERENCES dw.dim_year(year_key),
    nominee          TEXT,                                    -- degenerate: awarded work
    award_count      SMALLINT NOT NULL DEFAULT 1 CHECK (award_count = 1),
    CONSTRAINT uq_fact_grammy_award_grain UNIQUE (award_id, artist_key)
);
CREATE INDEX IF NOT EXISTS ix_fga_artist   ON dw.fact_grammy_award (artist_key);
CREATE INDEX IF NOT EXISTS ix_fga_category ON dw.fact_grammy_award (category_key);
CREATE INDEX IF NOT EXISTS ix_fga_year     ON dw.fact_grammy_award (year_key);